all:
	pdflatex Quispe_Condori_Hanan_Ronaldo
	bibtex Quispe_Condori_Hanan_Ronaldo
	pdflatex Quispe_Condori_Hanan_Ronaldo
clean: 
	rm -f *.aux *.bbl *.log *.blg *.dvi *.toc

cleanall: clean
	rm -f Quispe_Condori_Hanan_Ronaldo.pdf