all:
	pdflatex Quispe_Condori_Hanan_Ronaldo_Robotica
	bibtex Quispe_Condori_Hanan_Ronaldo_Robotica
	pdflatex Quispe_Condori_Hanan_Ronaldo_Robotica
clean: 
	rm -f *.aux *.bbl *.log *.blg *.dvi *.toc

cleanall: clean
	rm -f Quispe_Condori_Hanan_Ronaldo_Robotica.pdf